name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:

      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-python@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
          
      - name: install splint
        run: |
          sudo apt -y install splint \\
          pip install cpplint
      - name: check directory
        run: |
          ls -la
          
          
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        working-directory: ./
        run: |
          cpplint *.c |reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review -filter-mode=nofilter
      
