# https://github.com/marketplace/actions/build-and-push-docker-images
name: tags-test

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    env: 
      VERSION: 0
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repo 
        uses: actions/checkout@v2
      - 
        name: Detect Tags
        run: echo ${{ github.ref }} | sed -e "s#refs/tags/v\(.*\)#VERSION=\1#g" >> $GITHUB_ENV
      -
        name: show varsion
        run: |
          echo $VERSION && echo ${{env.VERSION}}
        
